Try new reorg check
zelcash/zelcash pull request #131
Opened 2021-03-29 03:39 UTC by blondfrogs

2021-03-29 03:47 UTC, TheTrunk approved these changes

2021-04-01 08:28 UTC, Cabecinha84 requested changes
Can we just apply this max reorglenght after block x? because before the number was much higher, and sometimes a daemon fails to sync from scratch when encounters a higher max reorg from a old block.

2021-04-01 08:42 UTC, TheTrunk commented
This PR fixes the issues with syncing as previously node could get just stuck without following its old chain waiting for user restart or action.
I believe it shall resolve the issue you are mentioning

2021-04-01 08:44 UTC, Cabecinha84 approved these changes
Ack

2021-04-01 11:52 UTC, merged