Ability to run from any dir fix
zelcash/zelcash pull request #137
Opened 2021-04-22 20:41 UTC by XK4MiLX

- added ability to detect zelbenchd/fluxbenchd
- added self path detection ( daemon will always look for zelbenchd/fluxbend on dir where is daemon )

2021-04-22 21:09 UTC, Cabecinha84 approved these changes
Ack.

2021-04-23 12:24 UTC, TheTrunk commented on src/zelnode/benchmarks.cpp
> +    strBenchmarkCliPathing = getExePath();
strBenchmarkCliPathing variable name should be named differently as the function serves purpose for both daemon and cli

2021-04-23 12:28 UTC, TheTrunk commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
missing declarration in header file

2021-04-23 12:28 UTC, TheTrunk commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
Why not put the logic of it to FindBenchmarkPath function?

2021-04-23 12:33 UTC, TheTrunk requested changes

2021-04-23 12:33 UTC, TheTrunk commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
can you explain how the function works? What is the performance penalty? If we have a very large filesystem then it can be quite heavy call. Finding executable across whole system is not trivial task and this method can be called very oftenly and there is no caching present.

2021-04-23 13:06 UTC, XK4MiLX commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
logical function will not make it run from any dir

2021-04-23 13:33 UTC, XK4MiLX reviewed
strBenchmarkCliPathing is same for daemon and cli i dont renamed just used exist one it can be change due it hold path for both

2021-04-23 13:33 UTC, XK4MiLX commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
function using  /proc/self/exe to check self dir ;) it not looking for file so it is not havy ;) and deamon and benchmark are always in same dir so this way is convinient

2021-04-23 13:37 UTC, XK4MiLX commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
it is not needed due it is called from function that is already in header it is not called separatly  anywhere

2021-04-23 13:37 UTC, XK4MiLX commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
but can be add there

2021-04-23 13:40 UTC, XK4MiLX commented on src/zelnode/benchmarks.cpp
> +    strBenchmarkCliPathing = getExePath();
all idea is using one variable to both due it is same and  it can be call strPath

2021-04-23 13:53 UTC, XK4MiLX commented on src/zelnode/benchmarks.cpp
> +std::string getExePath()
This function finding current executable's path of daemon ;)

2021-04-27 21:47 UTC, blondfrogs reviewed
These changes seem fine. However, have they been tested? Do they work with both zelcash-cli ,fluxbench-cli, and the other daemons?

2021-04-29 01:35 UTC, TheTrunk approved these changes
tAck

2021-04-29 01:35 UTC, merged